### ISSUE TITLE
The Ora official API has been updated, which caused an error in the program, showing {"error":{"message":"Missing request referer"}}. It means that the program is missing a referer value.

### ISSUE THREAD

**Issue by taiyi747** [xtekky/openai-gpt4#12]
The Ora official API has been updated, which caused an error in the program, showing {"error":{"message":"Missing request referer"}}. It means that the program is missing a referer value.

**Comment by taiyi747** [comment]
I'm still a beginner and I tried to fix it, but I can't find a way to obtain this value.

**Comment by pingvi92** [comment]
the same

**Comment by xtekky** [comment]
Hi please try installing the latest version of this repository, I just checked the quora api with gpt-4 and a fresh token and it works perfectly fine, an other alternative is installing the `poe-api` pypi package and using it with the token you can generate using `quora.Account.create()`

**Comment by taiyi747** [comment]
> 

Excuse me, did you read it wrong? I'm referring to https://orazz.com/

**Comment by xtekky** [comment]
oh, I did read it wrong, will take a look later, closing this issue as I am going to update it now
