### ISSUE TITLE
t3nsor.tech is down

### ISSUE THREAD

**Issue by IntelligenzaArtificiale** [xtekky/openai-gpt4#13]
https://www.t3nsor.tech/ is down 

![image](https://user-images.githubusercontent.com/108482353/231085349-2e77d575-4962-40f5-a54e-d32213499546.png)

**Comment by xtekky** [comment]
yes I am aware, I can't do anything for now but will there be updates, I will update this repo

**Comment by xtekky** [comment]
solved

**Comment by tiagorangel2011** [comment]
down again
