### ISSUE TITLE
quora socket already open error!

### ISSUE THREAD

**Issue by lazezo2** [xtekky/openai-gpt4#17]
using quora API, i can receive response for 8-10 questions to chatgpt later 
a lot of error message socket already open error!, then API terminate!
i use random wait time between question and the next one, my random time is 30-60 second
     
     model_type = "gpt-3.5"
     token = ""   
    
    for response in quora.StreamingCompletion.create(model  = model_type,
        prompt = text1,
        token  = token):
    
    #print(response.completion.choices[0].text, end="", flush=True)

    # wait
    random_time = random.randint(30, 60)
    time.sleep(random_time)
    
    for response in quora.StreamingCompletion.create(model  = model_type,
        prompt = text1,
        token  = token):
    
    #print(response.completion.choices[0].text, end="", flush=True)
   
    # repeat same steps with different text1 cause error after 8 text1!!
do i have to increase the wait time?
or what 's wrong?
any suggestion?

**Comment by lazezo2** [comment]
i increase wait time and it work but after 20 minutes another error raise

> Traceback (most recent call last):
  File "openai-gpt4-main\quora\api.py", line 314, in send_message
    message = self.message_queues[human_message_id].get(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python\Python311\Lib\queue.py", lin
e 179, in get
    raise Empty
_queue.Empty

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "openai-gpt4-main\quora.py", line 504, in <module>
>    post_to_chatgpt()
> 

  

> File "openai-gpt4-main\quora.py", line 186, in post_to_chatgpt
>     for response in quora.StreamingCompletion.create(model  = model_type,
>   File "openai-gpt4-main\quora\__init__.py", line 158, in create
>     for chunk in client.send_message(models[model], prompt):
>   File "openai-gpt4-main\quora\api.py", line 319, in send_message
>     raise RuntimeError("Response timed out.")
> RuntimeError: Response timed out.

tried to catch the error, wait and retry but didn't catch he error
```python

 try:
  for response in quora.StreamingCompletion.create(model  = model_type,
    prompt = text1,
    token  = token):
except ValueError as err:
    print(err.args)
    wait.sleep(4*60)
   # retry again also with try and except
``` 
but sees not catching error so wait and retry didn't work
any help how to wait if error happen then resume?
i use constant token at began of script, is that wrong?
do i have to create token every time i send txt?

any help

**Comment by xtekky** [comment]
@lazezo2, I would suggest using the `poe-api`pypi package with tokens generated with `quora.Account.create`, it may solve your problem, even if this repo contains a local version of the mentionned package

repo of `poe-api`: https://github.com/ading2210/poe-api

**Comment by xtekky** [comment]
closing as I think this issue is resolved, reopen if more help is needed
