### ISSUE TITLE
Confused on how to use this.

### ISSUE THREAD

**Issue by savvyzimmer** [xtekky/openai-gpt4#19]
Hello,

I'm confused on how to use this stuff? Which python script do I run? Please help.

**Comment by xtekky** [comment]
hi, just download the repository, you will then have a folder named openai-gpt4 which you can open then you will have the folders qora, t3nsor... which u can then import into a script you create in the base folder (openai-gpt4) various use cases are shown in the readme file 

this repo is intended for client use and is not intended to use like a website 

I assume u came here to use gpt-4 you can use sites like bing.com/chat or my site xtekky.com if you are not familiar with languages like python or programming at all

let me know if you need more help @savvyzimmer

**Comment by savvyzimmer** [comment]
Thank you for your help. I understand now. I will use your site thank you! (btw awesome site very well designed)

**Comment by xtekky** [comment]
Thanks, but I would suggest to just use chat.openai.com or bing.com/chat as they have better uptime and stability
