### ISSUE TITLE
ora.sh token creation problem

### ISSUE THREAD

**Issue by sihai2933** [xtekky/openai-gpt4#21]
![image](https://user-images.githubusercontent.com/103745513/231931441-cb4558ca-a8fb-4dce-a56e-2ff3bb71a7e6.png)
I used sample code for testing and have output email and send_ code、verify_ Code, 
but it stays here a long time, and the response result cannot be output.
Where is the problem? Thks.

**Comment by xtekky** [comment]
closing as i will open general issue
