### ISSUE TITLE
It keeps giving the error Bad Request on token creation

### ISSUE THREAD

**Issue by dolodi** [xtekky/openai-gpt4#22]
email yuymnrmvjs@bugfoo.com
bad request, retrying... {'success': False, 'message': 'Bad Request'}
email luzmuxcnli@bugfoo.com
bad request, retrying... {'success': False, 'message': 'Bad Request'}

This is the code running.

import quora
from time import sleep

token = quora.Account.create(proxy = None,logging = True, enable_bot_creation=True)
print('token', token)

**Comment by mnhcorp** [comment]
Just to chime in, I'm getting this too.

**Comment by xtekky** [comment]
yup its down, I have to fix it

**Comment by xtekky** [comment]
closing as I will make general issue
