### ISSUE TITLE
help needed reversing https://phind.com/

### ISSUE THREAD

**Issue by xtekky** [xtekky/openai-gpt4#23]
While reversing phind.com, I have encountered a hard cloudflare firewall which I could not bypass whatever I used, if you have any info or something that could help me, you may post it in this issue or create a pull request

**Comment by xtekky** [comment]
closing as I solved the problem

**Comment by r10rivas** [comment]
> closing as I solved the problem

Could you share how you solved the problem?
I'm having the same problem you described
