### ISSUE TITLE
poe not working

### ISSUE THREAD

**Issue by bartualev0** [xtekky/openai-gpt4#25]
I get this error

bad request, retrying... {'success': False, 'message': 'Bad Request'}

**Comment by bartualev0** [comment]
email ncltwtysok@bugfoo.com
send_code {'data': {'sendVerificationCode': {'status': 'user_with_confirmed_email_not_found', 'errorMessage': None}}, 'extensions': {'is_final': True}}
code 396659
verify_code {'data': None, 'errors': [{'message': 'Server Error'}], 'extensions': {'is_final': True}}

**Comment by xtekky** [comment]
yes, i will be trying to find another way, but all that remains is using paid services at this point

**Comment by xtekky** [comment]
closing as it is a duplicate
