### ISSUE TITLE
quora new patch

### ISSUE THREAD

**Issue by MaxAndolini** [xtekky/openai-gpt4#28]
`client.headers["poe-formkey"]  =  next_data['props']['formkey']`

Element 'formkey' does not exist in 'props'

**Comment by xtekky** [comment]
they have a generator function now, I will try to crack it     
<img width="751" alt="image" src="https://user-images.githubusercontent.com/98614666/232313608-07b40275-7060-43ad-bf79-041365392ef8.png">

**Comment by xtekky** [comment]
fixed
