### ISSUE TITLE
Can't use poe

### ISSUE THREAD

**Issue by Meksis** [xtekky/openai-gpt4#4]
Yesterday I tried to use poe and made some working code for tests. But now It doesn't work and raises an error:
```
  File "L:\Programms\Python\lib\site-packages\poe\__init__.py", line 85, in create
    next_data = loads(search(r'json">(.+?)</script>', init.text).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```
I didn't made any changes with lib.

**Comment by Meksis** [comment]
Forgot to mark that I initialize poe token by ```self.__gpt_4_token = poe.Account.create(logging = True)``` and response by ```response += poe.Completion.create(
                model  = 'gpt-4',
                prompt = prompt,
                token  = self.__gpt_4_token
            ).completion.choices[0].text```

**Comment by xtekky** [comment]
hi it works completely fine and I pushed an update, can u try again, if issues persist they are most likely due to altering the code
