### ISSUE TITLE
Error while using poe.com

### ISSUE THREAD

**Issue by Hdhwujddhwuj** [xtekky/openai-gpt4#6]
![IMG_20230405_093254](https://user-images.githubusercontent.com/114807196/229980363-16eeed3b-8ab1-4400-8532-e18cf5702654.jpg)
Hey,So i was testing your code for poe and it's giving me this error when I try to chat after getting token and putting it
Thx if u can help with it

**Comment by Hdhwujddhwuj** [comment]
t3nsor is also not working it's giving keyError in 'prompt _token'

**Comment by TurboPlayCraft** [comment]
I have same problem

**Comment by Caportabow** [comment]
same
