### ISSUE TITLE
Context management (chat history) for poe.com

### ISSUE THREAD

**Issue by nimagp** [xtekky/openai-gpt4#9]
poe.com is currently the best, but using it as a chatbot is impossible due to the lack of the option to send previous messages

**Comment by morelikeZaki** [comment]
> 

### heres a quick work-around that I'm using :

```
import poe

messages = {}
while True:
    prp = ""
    msg = input("you : ")
    for m in messages:
        prp += f"{m}:{messages[m]}"
    token = poe.Account.create()
    rpl = ""
    for response in poe.StreamingCompletion.create(model='gpt-4',
                                                   prompt=prp+msg,
                                                   token=token):

        print(response.completion.choices[0].text, end="", flush=True)
        rpl += response.completion.choices[0].text
    print("")
    messages.setdefault(msg, rpl)

```

**Comment by nimagp** [comment]
> > 
> 
> ### heres a quick work-around that I'm using :
> ```
> import poe
> 
> messages = {}
> while True:
>     prp = ""
>     msg = input("you : ")
>     for m in messages:
>         prp += f"{m}:{messages[m]}"
>     token = poe.Account.create()
>     rpl = ""
>     for response in poe.StreamingCompletion.create(model='gpt-4',
>                                                    prompt=prp+msg,
>                                                    token=token):
> 
>         print(response.completion.choices[0].text, end="", flush=True)
>         rpl += response.completion.choices[0].text
>     print("")
>     messages.setdefault(msg, rpl)
> ```

not quite the effect you'd expect it to have

**Comment by xtekky** [comment]
I will improve the poe api handler to be able to handle conversations, to use gpt-4 I suggest threading the account creation with proxies, although having a conversation with gpt-4 is impossible due to its one per account use

**Comment by xtekky** [comment]
After mode testing, I found out that the chat context management is already handled in the backend of poe.com
simply create a new bot and continue prompting it and it will remember previous messages
